# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awards', '0002_auto_20181011_0743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeveloperSite',
        ),
        migrations.DeleteModel(
            name='HonorableMention',
        ),
        migrations.DeleteModel(
            name='MobileOfWeek',
        ),
        migrations.DeleteModel(
            name='SiteOfDay',
        ),
        migrations.DeleteModel(
            name='SiteOfYear',
        ),
        migrations.AddField(
            model_name='commentslikes',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='awards.Comment'),
        ),
        migrations.AddField(
            model_name='commentslikes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postlikes',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='awards.Post'),
        ),
        migrations.AddField(
            model_name='postlikes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='awards.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='awards.Post'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='awards.Post'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='tag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
